/* English Comprehension — 6 papers, 12 questions each. All passages original. */
window.ENG_PASSAGES = [];
window.ENG_PAPERS = [];

/* ---------------- PAPER 1 ---------------- */
ENG_PASSAGES.push({title:"The Tide at Craster Cove", body:`
<p>Martha had promised their mother two things: that they would be back before five, and that they would not, under any circumstances, go beyond the rope barrier at the mouth of Craster Cove. She had kept the first promise for eleven years of her life. The second lasted less than an hour.</p>
<p>"It's only a cave," said Douglas, ducking beneath the frayed rope as though it were nothing more than a skipping rope held too low. "Caves don't belong to anyone."</p>
<p>Martha hesitated, glancing back along the empty beach. The tide was far out, a thin silver line stitched to the horizon, and the wet sand shone like polished pewter. Surely ten minutes could do no harm. She followed her brother into the dark.</p>
<p>Inside, the cave smelled of salt and old seaweed. Douglas's torch swept over walls glistening with damp, and picked out a ledge high above them where something pale gleamed. "Bones!" he whispered gleefully, though on closer inspection it proved to be nothing more sinister than a bleached driftwood branch.</p>
<p>It was the sound that warned Martha first — a low, hollow boom, like a door closing in a distant room. She turned. Where the cave mouth had framed a wide picture of sand, there was now a shifting sheet of grey water. The tide, which had seemed so lazily distant, had crept behind them like a thief.</p>
<p>"Douglas," she said, keeping her voice steady, "we're leaving. Now."</p>
<p>The water was knee-deep at the entrance and shockingly cold, tugging at their legs with an impatience that frightened her far more than the depth. Douglas stumbled; Martha gripped his wrist and hauled him forward, remembering, absurdly, a school assembly about rip currents that she had barely listened to at the time.</p>
<p>When at last they staggered onto dry sand, soaked to the waist, Douglas began to laugh — the wild, shaky laughter of someone who has been more afraid than he will ever admit. Martha did not laugh. She was looking at the rope barrier, snapping in the rising wind, and thinking about promises, and how quickly the sea takes back what people borrow from it.</p>`});

ENG_PAPERS.push([
{q:"What two things had Martha promised her mother?", opts:["To stay with Douglas and keep him dry","To be back before five and not to pass the rope barrier","To avoid the beach and be home for tea","To take a torch and stay out of the water"], a:1, ex:"The first paragraph says she promised to be back before five and not to go beyond the rope barrier."},
{q:"How long did Martha keep her second promise?", opts:["Eleven years","Ten minutes","Less than an hour","Until five o'clock"], a:2, ex:"The passage says the second promise 'lasted less than an hour'."},
{q:"The tide is described as 'a thin silver line stitched to the horizon'. What technique is this?", opts:["Alliteration","Onomatopoeia","A metaphor","A simile"], a:2, ex:"The tide is described as being a line 'stitched' to the horizon without using 'like' or 'as', so it is a metaphor."},
{q:"Why does Douglas duck under the rope 'as though it were nothing more than a skipping rope'?", opts:["He is frightened of the rope","He treats the barrier as unimportant","He wants to practise skipping","The rope is too high to climb over"], a:1, ex:"The comparison shows Douglas treats the serious barrier casually, as if it were a harmless toy."},
{q:"What did the pale object on the ledge turn out to be?", opts:["A bone","A piece of rope","A driftwood branch","A torch"], a:2, ex:"It 'proved to be nothing more sinister than a bleached driftwood branch'."},
{q:"What first warned Martha of the danger?", opts:["A sound like a distant door closing","Cold water around her knees","Douglas shouting","The torch going out"], a:0, ex:"'It was the sound that warned Martha first — a low, hollow boom, like a door closing.'"},
{q:"The tide 'had crept behind them like a thief'. What does this suggest about the tide?", opts:["It moved quietly and unnoticed","It stole their belongings","It moved very slowly all afternoon","It made a loud rushing noise"], a:0, ex:"A thief moves silently and secretly; the simile shows the tide came in without them noticing."},
{q:"What frightened Martha more than the depth of the water?", opts:["The darkness of the cave","The coldness of the water","The pulling force of the water","Douglas's laughter"], a:2, ex:"The water was 'tugging at their legs with an impatience that frightened her far more than the depth'."},
{q:"What does the word 'absurdly' suggest about Martha remembering the school assembly?", opts:["The assembly had been about caves","It seemed a strange moment to remember it","She remembered it perfectly","The assembly was very recent"], a:1, ex:"'Absurdly' means ridiculously — it felt odd that a half-ignored assembly popped into her head at that moment."},
{q:"Why does Douglas laugh at the end?", opts:["He thinks Martha looks funny soaking wet","He is relieved after being very frightened","He finds the cave amusing","He is laughing at the rope barrier"], a:1, ex:"His laughter is 'wild' and 'shaky' — the laughter of someone 'who has been more afraid than he will ever admit'."},
{q:"Which word best describes Martha's mood in the final paragraph?", opts:["Amused","Thoughtful","Furious","Bored"], a:1, ex:"She does not laugh; she looks at the rope and thinks about promises and the sea — she is reflective and thoughtful."},
{q:"What does the final sentence suggest the sea does?", opts:["It always stays far from the shore","It gives people gifts","It quickly reclaims the shore people walk on","It protects people who make promises"], a:2, ex:"'How quickly the sea takes back what people borrow from it' — the beach only 'belongs' to people while the tide allows it."}
]);

/* ---------------- PAPER 2 ---------------- */
ENG_PASSAGES.push({title:"The Secret Life of Honeybees", body:`
<p>To most of us, a honeybee is little more than a passing hum on a summer afternoon. Yet inside every hive operates one of the most sophisticated societies in the natural world — a bustling city of up to sixty thousand residents, in which every citizen has a job and no one is ever unemployed.</p>
<p>At the centre of this city is the queen. Contrary to popular belief, she does not rule; she is less a monarch than a factory, laying up to two thousand eggs a day in the summer months. The true decision-makers are the workers — all of them female — who progress through a strict career ladder as they age. A young worker begins as a cleaner, scrubbing empty cells until they gleam. Later she is promoted to nurse, feeding larvae, then to builder, producing wax from glands on her abdomen. Only in the final weeks of her short life does she graduate to the most dangerous job of all: forager.</p>
<p>Foragers may travel more than three miles from the hive in search of nectar, and it is here that the honeybee performs its most astonishing trick. When a forager discovers a rich patch of flowers, she returns to the hive and performs what scientists call the waggle dance — a figure-of-eight movement whose angle and duration tell her sisters the precise direction and distance of the food. She is, in effect, drawing a map with her own body.</p>
<p>The males, known as drones, lead easier but shorter lives. They do no foraging, no building and no cleaning; their sole purpose is to mate with a new queen. When autumn arrives and food grows scarce, the workers show little sentimentality: the drones are driven from the hive to perish in the cold.</p>
<p>Honeybees matter to humans for a simple reason: roughly one third of the food we eat depends on pollination, much of it carried out by bees. When a bee ferries pollen from blossom to blossom, she is not being generous — she is simply gathering food — yet the accidental gift she leaves behind keeps orchards fruiting and fields flowering. The next time you hear that hum on a summer afternoon, it may be worth remembering that you are listening to one of agriculture's hardest workers, commuting home from a three-mile shift.</p>`});

ENG_PAPERS.push([
{q:"Up to how many bees can live in one hive?", opts:["Two thousand","Six thousand","Sixteen thousand","Sixty thousand"], a:3, ex:"The hive is described as 'a bustling city of up to sixty thousand residents'."},
{q:"Why does the writer say the queen is 'less a monarch than a factory'?", opts:["She commands the workers all day","Her main role is producing eggs, not ruling","She builds the wax cells herself","She works on a production line"], a:1, ex:"She 'does not rule'; her job is laying up to two thousand eggs a day — constant production, like a factory."},
{q:"Who are the 'true decision-makers' in the hive?", opts:["The drones","The queen","The workers","The foragers only"], a:2, ex:"The passage states directly that 'the true decision-makers are the workers'."},
{q:"Which of these is the correct order of a worker bee's jobs?", opts:["Nurse, cleaner, builder, forager","Cleaner, nurse, builder, forager","Builder, cleaner, nurse, forager","Forager, builder, nurse, cleaner"], a:1, ex:"She begins as a cleaner, is promoted to nurse, then builder, and finally forager."},
{q:"Why might foraging be called 'the most dangerous job of all'?", opts:["It involves producing wax","It means leaving the safety of the hive and travelling far","Foragers must fight the queen","Foragers work only at night"], a:1, ex:"Foragers travel more than three miles from the hive, facing the outside world, unlike bees working safely inside."},
{q:"What information does the waggle dance give to other bees?", opts:["The direction and distance of food","The age of the forager","The number of flowers found","The temperature outside the hive"], a:0, ex:"The dance's 'angle and duration tell her sisters the precise direction and distance of the food'."},
{q:"The phrase 'drawing a map with her own body' means the forager…", opts:["scratches a map into the wax","uses her movements to communicate a route","carries a map back to the hive","flies in the shape of the flowers"], a:1, ex:"The dance itself acts like a map — her body's movements communicate where to go."},
{q:"In the passage, what is a drone?", opts:["A male bee","A young queen","A female worker","A type of flower"], a:0, ex:"'The males, known as drones…'"},
{q:"What happens to the drones in autumn?", opts:["They become foragers","They are forced out of the hive","They start cleaning cells","They fly south for winter"], a:1, ex:"When food grows scarce, 'the drones are driven from the hive to perish in the cold'."},
{q:"What does the word 'sentimentality' mean in the fourth paragraph?", opts:["Cruelty","Tender, emotional feeling","Intelligence","Hunger"], a:1, ex:"'Little sentimentality' means the workers show little soft-heartedness or emotion when expelling the drones."},
{q:"According to the passage, why does a bee spread pollen between flowers?", opts:["To be generous to plants","As an accidental result of gathering food","Because farmers train bees to do it","To mark flowers she has visited"], a:1, ex:"'She is not being generous — she is simply gathering food — yet the accidental gift she leaves behind…'"},
{q:"Roughly what fraction of our food depends on pollination?", opts:["One tenth","One third","One half","Three quarters"], a:1, ex:"'Roughly one third of the food we eat depends on pollination.'"}
]);

/* ---------------- PAPER 3 ---------------- */
ENG_PASSAGES.push({title:"The Station Clock", body:`
<p>September, 1940. The train had taken all day, stopping and starting through countryside that grew steadily greener and emptier, and Thomas had long since eaten the fish-paste sandwiches his mother had wrapped in brown paper that morning. Around his neck, on a loop of string, hung a cardboard label with his name printed on it, as though he were a parcel that might otherwise go astray.</p>
<p>The platform at Netherfold was smaller than any station he had ever seen — a single lamp, a wooden bench, and a large white clock whose hands stood at six exactly. The other evacuees were collected one by one: the Hartley twins by a farmer's wife with flour on her apron, and little Joan Pickles by the vicar, who carried her suitcase as if it were made of glass. Soon only Thomas remained, sitting beneath the clock with his gas-mask box on his knees.</p>
<p>He counted the minutes. Ten past. Quarter past. In London, at this hour, his street would be filling with the smell of a hundred suppers, and his mother would be pulling the blackout curtains across the windows. He swallowed hard and stared fiercely at his boots, because eleven-year-olds from Bermondsey did not cry on strange platforms.</p>
<p>At twenty-five past six, a bicycle clattered against the station railings and a tall woman strode onto the platform, cheeks pink, grey hair escaping from beneath a man's flat cap. "Thomas Ellery?" she called, in a voice that could probably be heard two fields away. "I'm Mrs Cartwright. I'm afraid my pig got out, and a pig waits for no one." She looked him up and down, taking in the label, the box, the tightly held cap. "Well," she said, more gently, "you look half-starved and three-quarters miserable. We can mend both."</p>
<p>She took his suitcase before he could object and marched out to the lane, where a second bicycle — a rusty one, with a basket — leaned against the hedge. "Can you ride?" she asked. Thomas, who had never owned a bicycle but had borrowed every one in his street, nodded. "Good lad. It's two miles, mostly downhill, and there's rabbit pie at the end of it."</p>
<p>And though the ache of home did not leave him — it would not leave him for many months — Thomas found, as the hedges rushed past in the last of the light, that it was surprisingly difficult to feel entirely wretched while freewheeling downhill towards a rabbit pie.</p>`});

ENG_PAPERS.push([
{q:"In which year is the story set?", opts:["1914","1940","1954","2004"], a:1, ex:"The passage opens 'September, 1940'."},
{q:"Why does Thomas wear a cardboard label around his neck?", opts:["It is a school badge","It shows his name so he isn't lost, like a parcel","It is his train ticket","It lists his ration allowance"], a:1, ex:"The label has his name 'as though he were a parcel that might otherwise go astray' — evacuees were labelled so they could be identified."},
{q:"The comparison of Thomas to 'a parcel' suggests he feels…", opts:["excited and important","treated like an object being sent away","proud of his label","heavier than usual"], a:1, ex:"A parcel is posted from place to place with no say in the matter — like an evacuee being sent away."},
{q:"Who collected Joan Pickles from the platform?", opts:["A farmer's wife","Mrs Cartwright","The vicar","The station master"], a:2, ex:"'Little Joan Pickles [was collected] by the vicar.'"},
{q:"What time does Mrs Cartwright arrive at the station?", opts:["Six o'clock","Ten past six","Quarter past six","Twenty-five past six"], a:3, ex:"'At twenty-five past six, a bicycle clattered against the station railings.'"},
{q:"Why does Thomas stare 'fiercely at his boots'?", opts:["His boots are new and shiny","He is trying not to cry","He is angry with Mrs Cartwright","He has dropped something"], a:1, ex:"He 'swallowed hard' and stared at his boots 'because eleven-year-olds from Bermondsey did not cry' — he is fighting back tears."},
{q:"Why was Mrs Cartwright late?", opts:["Her bicycle had a puncture","Her pig had escaped","She forgot the time","The train was early"], a:1, ex:"She explains: 'I'm afraid my pig got out, and a pig waits for no one.'"},
{q:"What does Mrs Cartwright mean by 'We can mend both'?", opts:["She will repair his suitcase and bicycle","She will feed him and cheer him up","She will fix the station clock","She will sew his label and cap"], a:1, ex:"He looks 'half-starved and three-quarters miserable'; she means she can cure his hunger and his unhappiness."},
{q:"What does the detail that Thomas 'had borrowed every [bicycle] in his street' suggest about him?", opts:["He is dishonest","He is wealthy","He is resourceful and well liked","He dislikes walking"], a:2, ex:"Never owning a bicycle but managing to ride everyone else's shows he is adaptable, friendly and makes the best of things."},
{q:"What does the word 'wretched' mean in the final paragraph?", opts:["Extremely unhappy","Very tired","Rather hungry","Slightly cold"], a:0, ex:"'Wretched' means miserable or deeply unhappy."},
{q:"Which statement about the ending is true?", opts:["Thomas forgets about home completely","Thomas stays sad but feels a small lift of hope","Thomas refuses to go with Mrs Cartwright","Thomas cries on the platform"], a:1, ex:"The 'ache of home did not leave him', yet he finds it hard to feel 'entirely wretched' — his sadness remains, but hope creeps in."},
{q:"The author's main purpose in this passage is to…", opts:["explain the history of wartime evacuation","persuade readers to visit the countryside","tell the story of a boy's arrival and first glimmer of comfort","describe how to ride a bicycle safely"], a:2, ex:"It is a narrative focused on Thomas's feelings as he arrives and begins, just slightly, to feel better."}
]);

/* ---------------- PAPER 4 ---------------- */
ENG_PASSAGES.push({title:"Urban Foxes: Neighbours in the Night", body:`
<p>At around two o'clock in the morning, when the last takeaway has closed and the buses run empty, the true owners of many British streets emerge. A dustbin lid shifts; a shadow slips along a garden wall; a pair of amber eyes catches the glow of a streetlamp. The red fox, once a creature of woodland and farmland, has become one of the most successful city dwellers in the country.</p>
<p>Foxes first moved into British towns in significant numbers during the 1930s, when new suburbs — with their large gardens, hedges and railway embankments — spread into the countryside. Rather than retreating, the foxes simply stayed put, and discovered that urban life suited them remarkably well. A city fox rarely needs to hunt in the way its rural cousins must. Instead, it dines on an extraordinary menu: discarded chips, windfall apples, earthworms pulled from lawns after rain, and food deliberately left out by admiring householders. Researchers who examined the stomach contents of urban foxes found that over half their diet comes, directly or indirectly, from humans.</p>
<p>Not everyone welcomes these bold neighbours. Gardeners complain of dug-up flowerbeds and stolen shoes — foxes are notorious collectors of footwear, which they carry off not to eat but seemingly to play with. Others object to the eerie scream of the vixen on winter nights, a sound so human that it is regularly reported to the police. Supporters, however, point out that foxes provide free pest control, consuming large numbers of rats and mice, and that attacks on people are vanishingly rare.</p>
<p>Perhaps the most remarkable thing about urban foxes is how quickly they have adapted. Studies show that city foxes are bolder than rural ones, willing to approach within metres of humans, and that some have learned the timing of bin collections in their territory. One Bristol fox, fitted with a tracking collar, was found to check the same fifteen gardens each night in a regular circuit, like a postman doing his round in reverse — collecting rather than delivering.</p>
<p>Love them or loathe them, urban foxes are here to stay. They ask for no permission and pay no rent, yet they were using these hills and hollows long before the streets were laid over them. It may be more accurate to say that we moved in with the foxes, rather than the other way around.</p>`});

ENG_PAPERS.push([
{q:"According to the passage, when do urban foxes become most active?", opts:["At dawn","In the early afternoon","At around two o'clock in the morning","Just after sunset"], a:2, ex:"The opening describes them emerging 'at around two o'clock in the morning'."},
{q:"When did foxes first move into British towns in large numbers?", opts:["The 1830s","The 1930s","The 1960s","The 1990s"], a:1, ex:"'Foxes first moved into British towns in significant numbers during the 1930s.'"},
{q:"How did foxes come to live in the suburbs?", opts:["They were released by farmers","They followed the railways from Scotland","The suburbs were built over their countryside and they stayed","They escaped from zoos"], a:2, ex:"New suburbs 'spread into the countryside. Rather than retreating, the foxes simply stayed put.'"},
{q:"How much of an urban fox's diet comes from humans, directly or indirectly?", opts:["About a quarter","About a tenth","Over half","Almost all of it"], a:2, ex:"Researchers found 'over half their diet comes, directly or indirectly, from humans'."},
{q:"Why do foxes steal shoes, according to the passage?", opts:["To eat the leather","Apparently to play with them","To line their dens","To trade them with other foxes"], a:1, ex:"They carry footwear off 'not to eat but seemingly to play with'."},
{q:"Why is the vixen's scream 'regularly reported to the police'?", opts:["It breaks noise regulations","It sounds disturbingly human","It frightens other animals","It happens during the day"], a:1, ex:"The scream is 'so human' that people mistake it for a person in trouble."},
{q:"Which argument do supporters of foxes make?", opts:["Foxes keep gardens tidy","Foxes eat large numbers of rats and mice","Foxes guard houses at night","Foxes are easy to tame"], a:1, ex:"Supporters 'point out that foxes provide free pest control, consuming large numbers of rats and mice'."},
{q:"What does 'vanishingly rare' suggest about fox attacks on people?", opts:["They happen every winter","They are so uncommon they barely exist","They are increasing each year","They only happen at night"], a:1, ex:"'Vanishingly rare' means so rare as to be almost non-existent."},
{q:"What had the Bristol fox with the tracking collar learned to do?", opts:["Open dustbin lids with its nose","Visit the same fifteen gardens in a nightly circuit","Follow the postman on his round","Cross roads at traffic lights"], a:1, ex:"It 'was found to check the same fifteen gardens each night in a regular circuit'."},
{q:"Why is the fox compared to 'a postman doing his round in reverse'?", opts:["It works in the early morning like a postman","It follows a regular route but collects instead of delivering","It wears a tracking collar like a uniform","It visits every house in the city"], a:1, ex:"A postman follows a set route delivering things; the fox follows a set route collecting food."},
{q:"What does the phrase 'They ask for no permission and pay no rent' emphasise?", opts:["Foxes are unwelcome criminals","Foxes live among us entirely on their own terms","Foxes should be charged for the food they take","Foxes are owned by the council"], a:1, ex:"It stresses their independence — they live in our streets without needing anything agreed by humans."},
{q:"What is the meaning of the final sentence?", opts:["Foxes recently invaded human cities","Humans built their homes on land foxes already lived on","Foxes and humans arrived at the same time","Foxes prefer the countryside to towns"], a:1, ex:"Foxes 'were using these hills and hollows long before the streets were laid' — so really humans moved into fox territory."}
]);

/* ---------------- PAPER 5 ---------------- */
ENG_PASSAGES.push({title:"The Clockwork Sparrow of Milliner's Lane", body:`
<p>Everyone on Milliner's Lane agreed that old Mr Fetterling was peculiar, though nobody could agree on precisely how. The baker said he had once seen him feeding biscuit crumbs to a pigeon and apologising to it for the weather. The schoolmistress said his shop — WATCHES & AUTOMATA, REPAIRS UNDERTAKEN — had not sold a single watch in twenty years. What everybody knew for certain was that his window display never changed: one dusty carriage clock, one velvet cushion, and a small brass sparrow with folded wings.</p>
<p>Ada passed the shop every morning on her way to school, and every morning the sparrow's glass eye seemed to follow her. On the last day of term, unable to bear the mystery a moment longer, she pushed open the door. A bell jangled somewhere in the dimness, and the smell of oil and metal shavings rose to meet her like a tide.</p>
<p>"Ah," said Mr Fetterling, appearing between towers of cogs and mainsprings, "the girl who looks. Most people only glance." He lifted the sparrow from the window with hands as gentle as a nurse's, wound a hidden key three times — no more, no less — and set it on the counter.</p>
<p>What happened next Ada would remember for the rest of her life. The brass wings unfolded with a whisper of sliding metal. The head tilted. Then the sparrow opened its beak and sang: not a tinny mechanical jingle, but a true dawn song, liquid and full, as if a summer morning had been captured, folded very small, and hidden inside the metal chest.</p>
<p>"It took me eleven years," said Mr Fetterling quietly. "Four hundred and six pieces. People ask me why I never sell it." He shut one eye and peered at Ada through a jeweller's lens, as if she too were a mechanism whose quality he was judging. "I don't keep it because it is valuable. I keep it because everyone who hears it looks the way you look now — and that expression, young lady, cannot be bought in any shop in England."</p>
<p>Ada floated home with her head full of brass feathers. She did not yet know that she would one day be apprenticed in that dim, ticking shop, nor that the sparrow would one day be hers. For now, it was enough to have heard a summer morning singing in December, on a grey little street where nothing was ever supposed to happen.</p>`});

ENG_PAPERS.push([
{q:"What did the baker claim to have seen Mr Fetterling doing?", opts:["Selling a watch","Apologising to a pigeon for the weather","Polishing the brass sparrow","Arguing with the schoolmistress"], a:1, ex:"The baker 'had once seen him feeding biscuit crumbs to a pigeon and apologising to it for the weather'."},
{q:"According to the schoolmistress, how long had the shop gone without selling a watch?", opts:["Eleven years","Four years","Twenty years","Six months"], a:2, ex:"His shop 'had not sold a single watch in twenty years'."},
{q:"Which three items were in the window display?", opts:["A watch, a key and a sparrow","A carriage clock, a velvet cushion and a brass sparrow","A cushion, a jeweller's lens and a clock","Three brass sparrows"], a:1, ex:"'One dusty carriage clock, one velvet cushion, and a small brass sparrow.'"},
{q:"What finally makes Ada enter the shop?", opts:["Mr Fetterling invites her in","She needs a watch repaired","She can no longer bear the mystery","She is sheltering from the rain"], a:2, ex:"On the last day of term, 'unable to bear the mystery a moment longer, she pushed open the door'."},
{q:"The smell 'rose to meet her like a tide' is an example of…", opts:["a simile","alliteration","onomatopoeia","a rhyme"], a:0, ex:"It compares the smell to a tide using 'like', so it is a simile."},
{q:"What does Mr Fetterling mean by calling Ada 'the girl who looks'?", opts:["She stares rudely at strangers","She pays real attention, unlike people who only glance","She looks like his granddaughter","She looks into every shop on the lane"], a:1, ex:"He contrasts her with most people, who 'only glance' — Ada notices things properly."},
{q:"How many times must the hidden key be wound?", opts:["Twice","Three times","Four times","Eleven times"], a:1, ex:"He 'wound a hidden key three times — no more, no less'."},
{q:"The sparrow's song is described as if 'a summer morning had been captured… and hidden inside the metal chest'. What does this convey?", opts:["The song sounds mechanical and tinny","The song is astonishingly real and beautiful","The sparrow only sings in summer","The chest contains a real bird"], a:1, ex:"The image suggests the song holds all the life and beauty of a real dawn — nothing like a mechanical jingle."},
{q:"How many pieces make up the sparrow?", opts:["Three hundred and six","Four hundred and six","Four hundred and sixteen","Six hundred and four"], a:1, ex:"'Four hundred and six pieces.'"},
{q:"Why does Mr Fetterling refuse to sell the sparrow?", opts:["No one can afford it","He treasures the wonder on listeners' faces, which money cannot buy","He has promised it to the baker","It is too fragile to move"], a:1, ex:"He keeps it because the expression of wonder it produces 'cannot be bought in any shop in England'."},
{q:"What does 'Ada floated home' suggest about her feelings?", opts:["She was exhausted","She felt light with joy and amazement","She was carried home by Mr Fetterling","She was daydreaming about the sea"], a:1, ex:"'Floated' shows she is so delighted and amazed that she barely feels the ground."},
{q:"What does the narrator reveal about Ada's future?", opts:["She will move away from Milliner's Lane","She will become Mr Fetterling's apprentice and own the sparrow","She will sell the sparrow","She will never return to the shop"], a:1, ex:"'She would one day be apprenticed in that dim, ticking shop' and 'the sparrow would one day be hers'."}
]);

/* ---------------- PAPER 6 ---------------- */
ENG_PASSAGES.push({title:"The Race to the South Pole", body:`
<p>In the summer of 1910, two ships slipped out of European harbours, both bound — though only one crew knew it — for the same square of ice at the bottom of the world. Aboard the Terra Nova was Captain Robert Falcon Scott of the British Navy, leading a large expedition of scientists, ponies and motor sledges. Aboard the Fram was the Norwegian Roald Amundsen, who had told almost nobody, not even most of his own crew, where he was really going. Only when it was too late to turn back did he send Scott a telegram of chilling politeness: "Beg leave to inform you Fram proceeding Antarctic."</p>
<p>The two leaders could hardly have been more different. Amundsen had spent years living with the Inuit peoples of the Arctic, learning to drive dog teams, to wear loose furs that trapped warm air, and to travel light and fast. Scott placed his faith in ponies, which sank in the snow and suffered terribly in the cold, and in experimental motor sledges, one of which fell through the ice before the journey had even begun and the rest of which broke down within days.</p>
<p>Amundsen's party of five, with fifty-two dogs, left their base on 19 October 1911 and moved with astonishing efficiency, laying supply depots and covering more than twenty miles on a good day. On 14 December 1911 they stood at the South Pole, where they planted the Norwegian flag and — in a gesture that mixed courtesy with cold triumph — left a tent containing a letter for Scott and a note asking him to forward it to the King of Norway, in case they did not survive the return.</p>
<p>Scott's five-man team, hauling their own sledges through soft snow, arrived thirty-four days later, on 17 January 1912. The sight of the Norwegian flag met them like a blow. "Great God!" Scott wrote in his diary. "This is an awful place and terrible enough for us to have laboured to it without the reward of priority."</p>
<p>The return journey became one of the most famous tragedies of exploration. Weakened by hunger, cold and scurvy, Scott's men died one by one; the final three, including Scott himself, perished in their tent in late March, just eleven miles from a depot of food and fuel. Yet in defeat Scott achieved a strange kind of victory: the diaries found beside his body, full of courage and devotion to his comrades, made him a legend, while the meticulous Amundsen — who had, after all, simply done everything right — was long remembered with respect rather than love.</p>`});

ENG_PAPERS.push([
{q:"In what year did both expeditions set sail?", opts:["1901","1910","1912","1921"], a:1, ex:"'In the summer of 1910, two ships slipped out of European harbours.'"},
{q:"What was the name of Scott's ship?", opts:["The Fram","The Endurance","The Terra Nova","The Discovery"], a:2, ex:"'Aboard the Terra Nova was Captain Robert Falcon Scott.'"},
{q:"Why is Amundsen's telegram described as having 'chilling politeness'?", opts:["It was sent from the freezing Antarctic","Its courteous words carried an unwelcome, rival message","It was written in Norwegian","It arrived damaged by ice"], a:1, ex:"The wording is formal and polite, but the message — that Amundsen was racing him — was cold and unwelcome news for Scott."},
{q:"From whom had Amundsen learned his polar travel techniques?", opts:["The British Navy","Norwegian scientists","The Inuit peoples of the Arctic","Antarctic whalers"], a:2, ex:"He 'had spent years living with the Inuit peoples of the Arctic', learning dog-driving and how to dress for the cold."},
{q:"What happened to one of Scott's motor sledges before the journey began?", opts:["It was stolen","It fell through the ice","It was left in England","It was given to Amundsen"], a:1, ex:"One 'fell through the ice before the journey had even begun'."},
{q:"On what date did Amundsen reach the South Pole?", opts:["19 October 1911","14 December 1911","17 January 1912","Late March 1912"], a:1, ex:"'On 14 December 1911 they stood at the South Pole.'"},
{q:"Why did Amundsen leave a letter addressed to the King of Norway with Scott?", opts:["To boast about his victory in public","So news of his success would survive even if he died returning","To ask Scott for supplies","To invite Scott to Norway"], a:1, ex:"The note asked Scott to forward it 'in case they did not survive the return' — proof of his achievement would still reach Norway."},
{q:"How many days after Amundsen did Scott reach the Pole?", opts:["Eleven","Twenty","Thirty-four","Fifty-two"], a:2, ex:"Scott's team 'arrived thirty-four days later'."},
{q:"'The sight of the Norwegian flag met them like a blow.' What does this simile convey?", opts:["The flag was flapping violently in the wind","The discovery hurt them like a physical hit","The men were attacked at the Pole","The flag blocked their path"], a:1, ex:"Seeing they had been beaten was as painful and stunning as being struck."},
{q:"How far were Scott's final three men from a depot of food and fuel when they died?", opts:["Eleven miles","Twenty miles","Thirty-four miles","Two miles"], a:0, ex:"They 'perished in their tent… just eleven miles from a depot of food and fuel'."},
{q:"What made Scott 'a legend' despite his defeat?", opts:["His scientific discoveries","His diaries, full of courage and devotion","His safe return to Britain","His victory over Amundsen"], a:1, ex:"'The diaries found beside his body, full of courage and devotion to his comrades, made him a legend.'"},
{q:"What contrast does the final sentence draw between the two explorers?", opts:["Scott was loved as a hero while Amundsen was merely respected","Amundsen was forgotten while Scott was respected","Both men were equally celebrated","Neither man was remembered"], a:0, ex:"Scott became a beloved legend, whereas Amundsen, who 'had simply done everything right', earned 'respect rather than love'."}
]);
