/* English Comprehension — 6 papers, 12 questions each. All passages original. */
window.ENG_PASSAGES = [];
window.ENG_PAPERS = [];

/* ---------------- PAPER 1 ---------------- */
ENG_PASSAGES.push({title:"The Tide at Craster Cove", body:`
<p>Martha had promised their mother two things: that they would be back before five, and that they would not, under any circumstances, go beyond the rope barrier at the mouth of Craster Cove. She had kept the first promise for eleven years of her life. The second lasted less than an hour.</p>
<p>"It's only a cave," said Douglas, ducking beneath the frayed rope as though it were nothing more than a skipping rope held too low. "Caves don't belong to anyone."</p>
<p>Martha hesitated, glancing back along the empty beach. The tide was far out, a thin silver line stitched to the horizon, and the wet sand shone like polished pewter. Surely ten minutes could do no harm. She followed her brother into the dark.</p>
<p>Inside, the cave smelled of salt and old seaweed. Douglas's torch swept over walls glistening with damp, and picked out a ledge high above them where something pale gleamed. "Bones!" he whispered gleefully, though on closer inspection it proved to be nothing more sinister than a bleached driftwood branch.</p>
<p>It was the sound that warned Martha first — a low, hollow boom, like a door closing in a distant room. She turned. Where the cave mouth had framed a wide picture of sand, there was now a shifting sheet of grey water. The tide, which had seemed so lazily distant, had crept behind them like a thief.</p>
<p>"Douglas," she said, keeping her voice steady, "we're leaving. Now."</p>
<p>The water was knee-deep at the entrance and shockingly cold, tugging at their legs with an impatience that frightened her far more than the depth. Douglas stumbled; Martha gripped his wrist and hauled him forward, remembering, absurdly, a school assembly about rip currents that she had barely listened to at the time.</p>
<p>When at last they staggered onto dry sand, soaked to the waist, Douglas began to laugh — the wild, shaky laughter of someone who has been more afraid than he will ever admit. Martha did not laugh. She was looking at the rope barrier, snapping in the rising wind, and thinking about promises, and how quickly the sea takes back what people borrow from it.</p>`});

ENG_PAPERS.push([
{q:"What two things had Martha promised her mother?", opts:["To stay with Douglas and keep him dry","To be back before five and not to pass the rope barrier","To avoid the beach and be home for tea","To take a torch and stay out of the water"], a:1, ex:"The first paragraph says she promised to be back before five and not to go beyond the rope barrier."},
{q:"How long did Martha keep her second promise?", opts:["Eleven years","Ten minutes","Less than an hour","Until five o'clock"], a:2, ex:"The passage says the second promise 'lasted less than an hour'."},
{q:"The tide is described as 'a thin silver line stitched to the horizon'. What technique is this?", opts:["Alliteration","Onomatopoeia","A metaphor","A simile"], a:2, ex:"The tide is described as being a line 'stitched' to the horizon without using 'like' or 'as', so it is a metaphor."},
{q:"Why does Douglas duck under the rope 'as though it were nothing more than a skipping rope'?", opts:["He is frightened of the rope","He treats the barrier as unimportant","He wants to practise skipping","The rope is too high to climb over"], a:1, ex:"The comparison shows Douglas treats the serious barrier casually, as if it were a harmless toy."},
{q:"What did the pale object on the ledge turn out to be?", opts:["A bone","A piece of rope","A driftwood branch","A torch"], a:2, ex:"It 'proved to be nothing more sinister than a bleached driftwood branch'."},
{q:"What first warned Martha of the danger?", opts:["A sound like a distant door closing","Cold water around her knees","Douglas shouting","The torch going out"], a:0, ex:"'It was the sound that warned Martha first — a low, hollow boom, like a door closing.'"},
{q:"The tide 'had crept behind them like a thief'. What does this suggest about the tide?", opts:["It moved quietly and unnoticed","It stole their belongings","It moved very slowly all afternoon","It made a loud rushing noise"], a:0, ex:"A thief moves silently and secretly; the simile shows the tide came in without them noticing."},
{q:"What frightened Martha more than the depth of the water?", opts:["The darkness of the cave","The coldness of the water","The pulling force of the water","Douglas's laughter"], a:2, ex:"The water was 'tugging at their legs with an impatience that frightened her far more than the depth'."},
{q:"What does the word 'absurdly' suggest about Martha remembering the school assembly?", opts:["The assembly had been about caves","It seemed a strange moment to remember it","She remembered it perfectly","The assembly was very recent"], a:1, ex:"'Absurdly' means ridiculously — it felt odd that a half-ignored assembly popped into her head at that moment."},
{q:"Why does Douglas laugh at the end?", opts:["He thinks Martha looks funny soaking wet","He is relieved after being very frightened","He finds the cave amusing","He is laughing at the rope barrier"], a:1, ex:"His laughter is 'wild' and 'shaky' — the laughter of someone 'who has been more afraid than he will ever admit'."},
{q:"Which word best describes Martha's mood in the final paragraph?", opts:["Amused","Thoughtful","Furious","Bored"], a:1, ex:"She does not laugh; she looks at the rope and thinks about promises and the sea — she is reflective and thoughtful."},
{q:"What does the final sentence suggest the sea does?", opts:["It always stays far from the shore","It gives people gifts","It quickly reclaims the shore people walk on","It protects people who make promises"], a:2, ex:"'How quickly the sea takes back what people borrow from it' — the beach only 'belongs' to people while the tide allows it."}
]);

/* ---------------- PAPER 2 ---------------- */
ENG_PASSAGES.push({title:"The Secret Life of Honeybees", body:`
<p>To most of us, a honeybee is little more than a passing hum on a summer afternoon. Yet inside every hive operates one of the most sophisticated societies in the natural world — a bustling city of up to sixty thousand residents, in which every citizen has a job and no one is ever unemployed.</p>
<p>At the centre of this city is the queen. Contrary to popular belief, she does not rule; she is less a monarch than a factory, laying up to two thousand eggs a day in the summer months. The true decision-makers are the workers — all of them female — who progress through a strict career ladder as they age. A young worker begins as a cleaner, scrubbing empty cells until they gleam. Later she is promoted to nurse, feeding larvae, then to builder, producing wax from glands on her abdomen. Only in the final weeks of her short life does she graduate to the most dangerous job of all: forager.</p>
<p>Foragers may travel more than three miles from the hive in search of nectar, and it is here that the honeybee performs its most astonishing trick. When a forager discovers a rich patch of flowers, she returns to the hive and performs what scientists call the waggle dance — a figure-of-eight movement whose angle and duration tell her sisters the precise direction and distance of the food. She is, in effect, drawing a map with her own body.</p>
<p>The males, known as drones, lead easier but shorter lives. They do no foraging, no building and no cleaning; their sole purpose is to mate with a new queen. When autumn arrives and food grows scarce, the workers show little sentimentality: the drones are driven from the hive to perish in the cold.</p>
<p>Honeybees matter to humans for a simple reason: roughly one third of the food we eat depends on pollination, much of it carried out by bees. When a bee ferries pollen from blossom to blossom, she is not being generous — she is simply gathering food — yet the accidental gift she leaves behind keeps orchards fruiting and fields flowering. The next time you hear that hum on a summer afternoon, it may be worth remembering that you are listening to one of agriculture's hardest workers, commuting home from a three-mile shift.</p>`});

ENG_PAPERS.push([
{q:"Up to how many bees can live in one hive?", opts:["Two thousand","Six thousand","Sixteen thousand","Sixty thousand"], a:3, ex:"The hive is described as 'a bustling city of up to sixty thousand residents'."},
{q:"Why does the writer say the queen is 'less a monarch than a factory'?", opts:["She commands the workers all day","Her main role is producing eggs, not ruling","She builds the wax cells herself","She works on a production line"], a:1, ex:"She 'does not rule'; her job is laying up to two thousand eggs a day — constant production, like a factory."},
{q:"Who are the 'true decision-makers' in the hive?", opts:["The drones","The queen","The workers","The foragers only"], a:2, ex:"The passage states directly that 'the true decision-makers are the workers'."},
{q:"Which of these is the correct order of a worker bee's jobs?", opts:["Nurse, cleaner, builder, forager","Cleaner, nurse, builder, forager","Builder, cleaner, nurse, forager","Forager, builder, nurse, cleaner"], a:1, ex:"She begins as a cleaner, is promoted to nurse, then builder, and finally forager."},
{q:"Why might foraging be called 'the most dangerous job of all'?", opts:["It involves producing wax","It means leaving the safety of the hive and travelling far","Foragers must fight the queen","Foragers work only at night"], a:1, ex:"Foragers travel more than three miles from the hive, facing the outside world, unlike bees working safely inside."},
{q:"What information does the waggle dance give to other bees?", opts:["The direction and distance of food","The age of the forager","The number of flowers found","The temperature outside the hive"], a:0, ex:"The dance's 'angle and duration tell her sisters the precise direction and distance of the food'."},
{q:"The phrase 'drawing a map with her own body' means the forager…", opts:["scratches a map into the wax","uses her movements to communicate a route","carries a map back to the hive","flies in the shape of the flowers"], a:1, ex:"The dance itself acts like a map — her body's movements communicate where to go."},
{q:"In the passage, what is a drone?", opts:["A male bee","A young queen","A female worker","A type of flower"], a:0, ex:"'The males, known as drones…'"},
{q:"What happens to the drones in autumn?", opts:["They become foragers","They are forced out of the hive","They start cleaning cells","They fly south for winter"], a:1, ex:"When food grows scarce, 'the drones are driven from the hive to perish in the cold'."},
{q:"What does the word 'sentimentality' mean in the fourth paragraph?", opts:["Cruelty","Tender, emotional feeling","Intelligence","Hunger"], a:1, ex:"'Little sentimentality' means the workers show little soft-heartedness or emotion when expelling the drones."},
{q:"According to the passage, why does a bee spread pollen between flowers?", opts:["To be generous to plants","As an accidental result of gathering food","Because farmers train bees to do it","To mark flowers she has visited"], a:1, ex:"'She is not being generous — she is simply gathering food — yet the accidental gift she leaves behind…'"},
{q:"Roughly what fraction of our food depends on pollination?", opts:["One tenth","One third","One half","Three quarters"], a:1, ex:"'Roughly one third of the food we eat depends on pollination.'"}
]);

/* ---------------- PAPER 3 ---------------- */
ENG_PASSAGES.push({title:"The Station Clock", body:`
<p>September, 1940. The train had taken all day, stopping and starting through countryside that grew steadily greener and emptier, and Thomas had long since eaten the fish-paste sandwiches his mother had wrapped in brown paper that morning. Around his neck, on a loop of string, hung a cardboard label with his name printed on it, as though he were a parcel that might otherwise go astray.</p>
<p>The platform at Netherfold was smaller than any station he had ever seen — a single lamp, a wooden bench, and a large white clock whose hands stood at six exactly. The other evacuees were collected one by one: the Hartley twins by a farmer's wife with flour on her apron, and little Joan Pickles by the vicar, who carried her suitcase as if it were made of glass. Soon only Thomas remained, sitting beneath the clock with his gas-mask box on his knees.</p>
<p>He counted the minutes. Ten past. Quarter past. In London, at this hour, his street would be filling with the smell of a hundred suppers, and his mother would be pulling the blackout curtains across the windows. He swallowed hard and stared fiercely at his boots, because eleven-year-olds from Bermondsey did not cry on strange platforms.</p>
<p>At twenty-five past six, a bicycle clattered against the station railings and a tall woman strode onto the platform, cheeks pink, grey hair escaping from beneath a man's flat cap. "Thomas Ellery?" she called, in a voice that could probably be heard two fields away. "I'm Mrs Cartwright. I'm afraid my pig got out, and a pig waits for no one." She looked him up and down, taking in the label, the box, the tightly held cap. "Well," she said, more gently, "you look half-starved and three-quarters miserable. We can mend both."</p>
<p>She took his suitcase before he could object and marched out to the lane, where a second bicycle — a rusty one, with a basket — leaned against the hedge. "Can you ride?" she asked. Thomas, who had never owned a bicycle but had borrowed every one in his street, nodded. "Good lad. It's two miles, mostly downhill, and there's rabbit pie at the end of it."</p>
<p>And though the ache of home did not leave him — it would not leave him for many months — Thomas found, as the hedges rushed past in the last of the light, that it was surprisingly difficult to feel entirely wretched while freewheeling downhill towards a rabbit pie.</p>`});

ENG_PAPERS.push([
{q:"In which year is the story set?", opts:["1914","1940","1954","2004"], a:1, ex:"The passage opens 'September, 1940'."},
{q:"Why does Thomas wear a cardboard label around his neck?", opts:["It is a school badge","It shows his name so he isn't lost, like a parcel","It is his train ticket","It lists his ration allowance"], a:1, ex:"The label has his name 'as though he were a parcel that might otherwise go astray' — evacuees were labelled so they could be identified."},
{q:"The comparison of Thomas to 'a parcel' suggests he feels…", opts:["excited and important","treated like an object being sent away","proud of his label","heavier than usual"], a:1, ex:"A parcel is posted from place to place with no say in the matter — like an evacuee being sent away."},
{q:"Who collected Joan Pickles from the platform?", opts:["A farmer's wife","Mrs Cartwright","The vicar","The station master"], a:2, ex:"'Little Joan Pickles [was collected] by the vicar.'"},
{q:"What time does Mrs Cartwright arrive at the station?", opts:["Six o'clock","Ten past six","Quarter past six","Twenty-five past six"], a:3, ex:"'At twenty-five past six, a bicycle clattered against the station railings.'"},
{q:"Why does Thomas stare 'fiercely at his boots'?", opts:["His boots are new and shiny","He is trying not to cry","He is angry with Mrs Cartwright","He has dropped something"], a:1, ex:"He 'swallowed hard' and stared at his boots 'because eleven-year-olds from Bermondsey did not cry' — he is fighting back tears."},
{q:"Why was Mrs Cartwright late?", opts:["Her bicycle had a puncture","Her pig had escaped","She forgot the time","The train was early"], a:1, ex:"She explains: 'I'm afraid my pig got out, and a pig waits for no one.'"},
{q:"What does Mrs Cartwright mean by 'We can mend both'?", opts:["She will repair his suitcase and bicycle","She will feed him and cheer him up","She will fix the station clock","She will sew his label and cap"], a:1, ex:"He looks 'half-starved and three-quarters miserable'; she means she can cure his hunger and his unhappiness."},
{q:"What does the detail that Thomas 'had borrowed every [bicycle] in his street' suggest about him?", opts:["He is dishonest","He is wealthy","He is resourceful and well liked","He dislikes walking"], a:2, ex:"Never owning a bicycle but managing to ride everyone else's shows he is adaptable, friendly and makes the best of things."},
{q:"What does the word 'wretched' mean in the final paragraph?", opts:["Extremely unhappy","Very tired","Rather hungry","Slightly cold"], a:0, ex:"'Wretched' means miserable or deeply unhappy."},
{q:"Which statement about the ending is true?", opts:["Thomas forgets about home completely","Thomas stays sad but feels a small lift of hope","Thomas refuses to go with Mrs Cartwright","Thomas cries on the platform"], a:1, ex:"The 'ache of home did not leave him', yet he finds it hard to feel 'entirely wretched' — his sadness remains, but hope creeps in."},
{q:"The author's main purpose in this passage is to…", opts:["explain the history of wartime evacuation","persuade readers to visit the countryside","tell the story of a boy's arrival and first glimmer of comfort","describe how to ride a bicycle safely"], a:2, ex:"It is a narrative focused on Thomas's feelings as he arrives and begins, just slightly, to feel better."}
]);

/* ---------------- PAPER 4 ---------------- */
ENG_PASSAGES.push({title:"Urban Foxes: Neighbours in the Night", body:`
<p>At around two o'clock in the morning, when the last takeaway has closed and the buses run empty, the true owners of many British streets emerge. A dustbin lid shifts; a shadow slips along a garden wall; a pair of amber eyes catches the glow of a streetlamp. The red fox, once a creature of woodland and farmland, has become one of the most successful city dwellers in the country.</p>
<p>Foxes first moved into British towns in significant numbers during the 1930s, when new suburbs — with their large gardens, hedges and railway embankments — spread into the countryside. Rather than retreating, the foxes simply stayed put, and discovered that urban life suited them remarkably well. A city fox rarely needs to hunt in the way its rural cousins must. Instead, it dines on an extraordinary menu: discarded chips, windfall apples, earthworms pulled from lawns after rain, and food deliberately left out by admiring householders. Researchers who examined the stomach contents of urban foxes found that over half their diet comes, directly or indirectly, from humans.</p>
<p>Not everyone welcomes these bold neighbours. Gardeners complain of dug-up flowerbeds and stolen shoes — foxes are notorious collectors of footwear, which they carry off not to eat but seemingly to play with. Others object to the eerie scream of the vixen on winter nights, a sound so human that it is regularly reported to the police. Supporters, however, point out that foxes provide free pest control, consuming large numbers of rats and mice, and that attacks on people are vanishingly rare.</p>
<p>Perhaps the most remarkable thing about urban foxes is how quickly they have adapted. Studies show that city foxes are bolder than rural ones, willing to approach within metres of humans, and that some have learned the timing of bin collections in their territory. One Bristol fox, fitted with a tracking collar, was found to check the same fifteen gardens each night in a regular circuit, like a postman doing his round in reverse — collecting rather than delivering.</p>
<p>Love them or loathe them, urban foxes are here to stay. They ask for no permission and pay no rent, yet they were using these hills and hollows long before the streets were laid over them. It may be more accurate to say that we moved in with the foxes, rather than the other way around.</p>`});

ENG_PAPERS.push([
{q:"According to the passage, when do urban foxes become most active?", opts:["At dawn","In the early afternoon","At around two o'clock in the morning","Just after sunset"], a:2, ex:"The opening describes them emerging 'at around two o'clock in the morning'."},
{q:"When did foxes first move into British towns in large numbers?", opts:["The 1830s","The 1930s","The 1960s","The 1990s"], a:1, ex:"'Foxes first moved into British towns in significant numbers during the 1930s.'"},
{q:"How did foxes come to live in the suburbs?", opts:["They were released by farmers","They followed the railways from Scotland","The suburbs were built over their countryside and they stayed","They escaped from zoos"], a:2, ex:"New suburbs 'spread into the countryside. Rather than retreating, the foxes simply stayed put.'"},
{q:"How much of an urban fox's diet comes from humans, directly or indirectly?", opts:["About a quarter","About a tenth","Over half","Almost all of it"], a:2, ex:"Researchers found 'over half their diet comes, directly or indirectly, from humans'."},
{q:"Why do foxes steal shoes, according to the passage?", opts:["To eat the leather","Apparently to play with them","To line their dens","To trade them with other foxes"], a:1, ex:"They carry footwear off 'not to eat but seemingly to play with'."},
{q:"Why is the vixen's scream 'regularly reported to the police'?", opts:["It breaks noise regulations","It sounds disturbingly human","It frightens other animals","It happens during the day"], a:1, ex:"The scream is 'so human' that people mistake it for a person in trouble."},
{q:"Which argument do supporters of foxes make?", opts:["Foxes keep gardens tidy","Foxes eat large numbers of rats and mice","Foxes guard houses at night","Foxes are easy to tame"], a:1, ex:"Supporters 'point out that foxes provide free pest control, consuming large numbers of rats and mice'."},
{q:"What does 'vanishingly rare' suggest about fox attacks on people?", opts:["They happen every winter","They are so uncommon they barely exist","They are increasing each year","They only happen at night"], a:1, ex:"'Vanishingly rare' means so rare as to be almost non-existent."},
{q:"What had the Bristol fox with the tracking collar learned to do?", opts:["Open dustbin lids with its nose","Visit the same fifteen gardens in a nightly circuit","Follow the postman on his round","Cross roads at traffic lights"], a:1, ex:"It 'was found to check the same fifteen gardens each night in a regular circuit'."},
{q:"Why is the fox compared to 'a postman doing his round in reverse'?", opts:["It works in the early morning like a postman","It follows a regular route but collects instead of delivering","It wears a tracking collar like a uniform","It visits every house in the city"], a:1, ex:"A postman follows a set route delivering things; the fox follows a set route collecting food."},
{q:"What does the phrase 'They ask for no permission and pay no rent' emphasise?", opts:["Foxes are unwelcome criminals","Foxes live among us entirely on their own terms","Foxes should be charged for the food they take","Foxes are owned by the council"], a:1, ex:"It stresses their independence — they live in our streets without needing anything agreed by humans."},
{q:"What is the meaning of the final sentence?", opts:["Foxes recently invaded human cities","Humans built their homes on land foxes already lived on","Foxes and humans arrived at the same time","Foxes prefer the countryside to towns"], a:1, ex:"Foxes 'were using these hills and hollows long before the streets were laid' — so really humans moved into fox territory."}
]);

/* ---------------- PAPER 5 ---------------- */
ENG_PASSAGES.push({title:"The Clockwork Sparrow of Milliner's Lane", body:`
<p>Everyone on Milliner's Lane agreed that old Mr Fetterling was peculiar, though nobody could agree on precisely how. The baker said he had once seen him feeding biscuit crumbs to a pigeon and apologising to it for the weather. The schoolmistress said his shop — WATCHES & AUTOMATA, REPAIRS UNDERTAKEN — had not sold a single watch in twenty years. What everybody knew for certain was that his window display never changed: one dusty carriage clock, one velvet cushion, and a small brass sparrow with folded wings.</p>
<p>Ada passed the shop every morning on her way to school, and every morning the sparrow's glass eye seemed to follow her. On the last day of term, unable to bear the mystery a moment longer, she pushed open the door. A bell jangled somewhere in the dimness, and the smell of oil and metal shavings rose to meet her like a tide.</p>
<p>"Ah," said Mr Fetterling, appearing between towers of cogs and mainsprings, "the girl who looks. Most people only glance." He lifted the sparrow from the window with hands as gentle as a nurse's, wound a hidden key three times — no more, no less — and set it on the counter.</p>
<p>What happened next Ada would remember for the rest of her life. The brass wings unfolded with a whisper of sliding metal. The head tilted. Then the sparrow opened its beak and sang: not a tinny mechanical jingle, but a true dawn song, liquid and full, as if a summer morning had been captured, folded very small, and hidden inside the metal chest.</p>
<p>"It took me eleven years," said Mr Fetterling quietly. "Four hundred and six pieces. People ask me why I never sell it." He shut one eye and peered at Ada through a jeweller's lens, as if she too were a mechanism whose quality he was judging. "I don't keep it because it is valuable. I keep it because everyone who hears it looks the way you look now — and that expression, young lady, cannot be bought in any shop in England."</p>
<p>Ada floated home with her head full of brass feathers. She did not yet know that she would one day be apprenticed in that dim, ticking shop, nor that the sparrow would one day be hers. For now, it was enough to have heard a summer morning singing in December, on a grey little street where nothing was ever supposed to happen.</p>`});

ENG_PAPERS.push([
{q:"What did the baker claim to have seen Mr Fetterling doing?", opts:["Selling a watch","Apologising to a pigeon for the weather","Polishing the brass sparrow","Arguing with the schoolmistress"], a:1, ex:"The baker 'had once seen him feeding biscuit crumbs to a pigeon and apologising to it for the weather'."},
{q:"According to the schoolmistress, how long had the shop gone without selling a watch?", opts:["Eleven years","Four years","Twenty years","Six months"], a:2, ex:"His shop 'had not sold a single watch in twenty years'."},
{q:"Which three items were in the window display?", opts:["A watch, a key and a sparrow","A carriage clock, a velvet cushion and a brass sparrow","A cushion, a jeweller's lens and a clock","Three brass sparrows"], a:1, ex:"'One dusty carriage clock, one velvet cushion, and a small brass sparrow.'"},
{q:"What finally makes Ada enter the shop?", opts:["Mr Fetterling invites her in","She needs a watch repaired","She can no longer bear the mystery","She is sheltering from the rain"], a:2, ex:"On the last day of term, 'unable to bear the mystery a moment longer, she pushed open the door'."},
{q:"The smell 'rose to meet her like a tide' is an example of…", opts:["a simile","alliteration","onomatopoeia","a rhyme"], a:0, ex:"It compares the smell to a tide using 'like', so it is a simile."},
{q:"What does Mr Fetterling mean by calling Ada 'the girl who looks'?", opts:["She stares rudely at strangers","She pays real attention, unlike people who only glance","She looks like his granddaughter","She looks into every shop on the lane"], a:1, ex:"He contrasts her with most people, who 'only glance' — Ada notices things properly."},
{q:"How many times must the hidden key be wound?", opts:["Twice","Three times","Four times","Eleven times"], a:1, ex:"He 'wound a hidden key three times — no more, no less'."},
{q:"The sparrow's song is described as if 'a summer morning had been captured… and hidden inside the metal chest'. What does this convey?", opts:["The song sounds mechanical and tinny","The song is astonishingly real and beautiful","The sparrow only sings in summer","The chest contains a real bird"], a:1, ex:"The image suggests the song holds all the life and beauty of a real dawn — nothing like a mechanical jingle."},
{q:"How many pieces make up the sparrow?", opts:["Three hundred and six","Four hundred and six","Four hundred and sixteen","Six hundred and four"], a:1, ex:"'Four hundred and six pieces.'"},
{q:"Why does Mr Fetterling refuse to sell the sparrow?", opts:["No one can afford it","He treasures the wonder on listeners' faces, which money cannot buy","He has promised it to the baker","It is too fragile to move"], a:1, ex:"He keeps it because the expression of wonder it produces 'cannot be bought in any shop in England'."},
{q:"What does 'Ada floated home' suggest about her feelings?", opts:["She was exhausted","She felt light with joy and amazement","She was carried home by Mr Fetterling","She was daydreaming about the sea"], a:1, ex:"'Floated' shows she is so delighted and amazed that she barely feels the ground."},
{q:"What does the narrator reveal about Ada's future?", opts:["She will move away from Milliner's Lane","She will become Mr Fetterling's apprentice and own the sparrow","She will sell the sparrow","She will never return to the shop"], a:1, ex:"'She would one day be apprenticed in that dim, ticking shop' and 'the sparrow would one day be hers'."}
]);

/* ---------------- PAPER 6 ---------------- */
ENG_PASSAGES.push({title:"The Race to the South Pole", body:`
<p>In the summer of 1910, two ships slipped out of European harbours, both bound — though only one crew knew it — for the same square of ice at the bottom of the world. Aboard the Terra Nova was Captain Robert Falcon Scott of the British Navy, leading a large expedition of scientists, ponies and motor sledges. Aboard the Fram was the Norwegian Roald Amundsen, who had told almost nobody, not even most of his own crew, where he was really going. Only when it was too late to turn back did he send Scott a telegram of chilling politeness: "Beg leave to inform you Fram proceeding Antarctic."</p>
<p>The two leaders could hardly have been more different. Amundsen had spent years living with the Inuit peoples of the Arctic, learning to drive dog teams, to wear loose furs that trapped warm air, and to travel light and fast. Scott placed his faith in ponies, which sank in the snow and suffered terribly in the cold, and in experimental motor sledges, one of which fell through the ice before the journey had even begun and the rest of which broke down within days.</p>
<p>Amundsen's party of five, with fifty-two dogs, left their base on 19 October 1911 and moved with astonishing efficiency, laying supply depots and covering more than twenty miles on a good day. On 14 December 1911 they stood at the South Pole, where they planted the Norwegian flag and — in a gesture that mixed courtesy with cold triumph — left a tent containing a letter for Scott and a note asking him to forward it to the King of Norway, in case they did not survive the return.</p>
<p>Scott's five-man team, hauling their own sledges through soft snow, arrived thirty-four days later, on 17 January 1912. The sight of the Norwegian flag met them like a blow. "Great God!" Scott wrote in his diary. "This is an awful place and terrible enough for us to have laboured to it without the reward of priority."</p>
<p>The return journey became one of the most famous tragedies of exploration. Weakened by hunger, cold and scurvy, Scott's men died one by one; the final three, including Scott himself, perished in their tent in late March, just eleven miles from a depot of food and fuel. Yet in defeat Scott achieved a strange kind of victory: the diaries found beside his body, full of courage and devotion to his comrades, made him a legend, while the meticulous Amundsen — who had, after all, simply done everything right — was long remembered with respect rather than love.</p>`});

ENG_PAPERS.push([
{q:"In what year did both expeditions set sail?", opts:["1901","1910","1912","1921"], a:1, ex:"'In the summer of 1910, two ships slipped out of European harbours.'"},
{q:"What was the name of Scott's ship?", opts:["The Fram","The Endurance","The Terra Nova","The Discovery"], a:2, ex:"'Aboard the Terra Nova was Captain Robert Falcon Scott.'"},
{q:"Why is Amundsen's telegram described as having 'chilling politeness'?", opts:["It was sent from the freezing Antarctic","Its courteous words carried an unwelcome, rival message","It was written in Norwegian","It arrived damaged by ice"], a:1, ex:"The wording is formal and polite, but the message — that Amundsen was racing him — was cold and unwelcome news for Scott."},
{q:"From whom had Amundsen learned his polar travel techniques?", opts:["The British Navy","Norwegian scientists","The Inuit peoples of the Arctic","Antarctic whalers"], a:2, ex:"He 'had spent years living with the Inuit peoples of the Arctic', learning dog-driving and how to dress for the cold."},
{q:"What happened to one of Scott's motor sledges before the journey began?", opts:["It was stolen","It fell through the ice","It was left in England","It was given to Amundsen"], a:1, ex:"One 'fell through the ice before the journey had even begun'."},
{q:"On what date did Amundsen reach the South Pole?", opts:["19 October 1911","14 December 1911","17 January 1912","Late March 1912"], a:1, ex:"'On 14 December 1911 they stood at the South Pole.'"},
{q:"Why did Amundsen leave a letter addressed to the King of Norway with Scott?", opts:["To boast about his victory in public","So news of his success would survive even if he died returning","To ask Scott for supplies","To invite Scott to Norway"], a:1, ex:"The note asked Scott to forward it 'in case they did not survive the return' — proof of his achievement would still reach Norway."},
{q:"How many days after Amundsen did Scott reach the Pole?", opts:["Eleven","Twenty","Thirty-four","Fifty-two"], a:2, ex:"Scott's team 'arrived thirty-four days later'."},
{q:"'The sight of the Norwegian flag met them like a blow.' What does this simile convey?", opts:["The flag was flapping violently in the wind","The discovery hurt them like a physical hit","The men were attacked at the Pole","The flag blocked their path"], a:1, ex:"Seeing they had been beaten was as painful and stunning as being struck."},
{q:"How far were Scott's final three men from a depot of food and fuel when they died?", opts:["Eleven miles","Twenty miles","Thirty-four miles","Two miles"], a:0, ex:"They 'perished in their tent… just eleven miles from a depot of food and fuel'."},
{q:"What made Scott 'a legend' despite his defeat?", opts:["His scientific discoveries","His diaries, full of courage and devotion","His safe return to Britain","His victory over Amundsen"], a:1, ex:"'The diaries found beside his body, full of courage and devotion to his comrades, made him a legend.'"},
{q:"What contrast does the final sentence draw between the two explorers?", opts:["Scott was loved as a hero while Amundsen was merely respected","Amundsen was forgotten while Scott was respected","Both men were equally celebrated","Neither man was remembered"], a:0, ex:"Scott became a beloved legend, whereas Amundsen, who 'had simply done everything right', earned 'respect rather than love'."}
]);

/* ---------------- PAPER 7 ---------------- */
ENG_PASSAGES.push({title:"The Lighthouse Keeper's Daughter", body:`
<p>The storm had been building all afternoon, and by nightfall it flung itself against the Longstone lighthouse as though it meant to tear the rock from the sea. Inside, Grace pressed her face to the salt-blurred glass and watched the waves climb higher than she had ever seen them. Her father, the keeper, had long since lit the great lamp; its beam swung out into the dark, catching the rain in silver sheets.</p>
<p>It was Grace who saw the wreck first. As the beam wheeled round, it lit, for half a second, the broken shape of a steamship dashed upon the rocks a quarter of a mile away. Clinging to what remained of the deck were a handful of survivors, so small against the black water that they might have been mistaken for seabirds.</p>
<p>"We must go to them," Grace said.</p>
<p>Her father shook his head. "No boat could live in that sea. And even if it could, the two of us could never row against it."</p>
<p>But Grace had already taken down the oars. She was not a large girl, nor a strong one, but she had rowed these waters since she was six years old, and she knew that if they waited for the storm to pass there would be no one left to save. Reluctantly, her father followed her down to the little cove where their rowing boat was moored.</p>
<p>What followed was an hour Grace would never fully be able to describe. The boat rose and fell like a leaf on a waterfall; twice it was nearly swamped; her arms burned until she could no longer feel them. Yet somehow, between them, they reached the wreck, dragged four half-drowned survivors aboard, and fought their way back to the lighthouse, where Grace's mother wrapped the shivering strangers in every blanket they owned.</p>
<p>When news of the rescue reached the mainland, Grace Darling became, quite against her wishes, the most famous young woman in the country. Poems were written about her; strangers sent her gifts; artists begged her to sit for portraits. But Grace never understood the fuss. She had seen people in danger and had done what needed doing. That, to her, was not heroism. It was simply what the daughter of a lighthouse keeper was for.</p>`});
ENG_PAPERS.push([
{q:"Where does this story take place?", opts:["On a mainland harbour","At the Longstone lighthouse","On board a steamship","In a fishing village"], a:1, ex:"The storm 'flung itself against the Longstone lighthouse', where Grace and her father live."},
{q:"What does the storm seem to want to do, according to the first paragraph?", opts:["Put out the lamp","Tear the rock from the sea","Sink every ship in England","Flood the lighthouse"], a:1, ex:"It flung itself at the lighthouse 'as though it meant to tear the rock from the sea'."},
{q:"Who saw the wreck first?", opts:["Grace's father","Grace","Grace's mother","One of the survivors"], a:1, ex:"'It was Grace who saw the wreck first.'"},
{q:"Why does the writer say the survivors 'might have been mistaken for seabirds'?", opts:["They were flapping their arms","They looked tiny and distant against the dark water","They were sitting on the rocks","They were dressed in white"], a:1, ex:"They were 'so small against the black water' that from a distance they resembled birds."},
{q:"What is Grace's father's first reaction to the idea of a rescue?", opts:["He agrees at once","He thinks it is impossible and too dangerous","He wants to fetch help from the mainland","He tells Grace to go alone"], a:1, ex:"He shakes his head, saying 'No boat could live in that sea' and that the two of them could never row against it."},
{q:"What convinces us Grace is capable of attempting the rescue despite her size?", opts:["She has a larger boat hidden away","She has rowed those waters since she was six","She has rescued people before","Her father is very strong"], a:1, ex:"Though 'not a large girl, nor a strong one', she 'had rowed these waters since she was six years old'."},
{q:"'The boat rose and fell like a leaf on a waterfall.' What does this simile suggest?", opts:["The boat was small and brightly coloured","The boat was tossed helplessly by the water","The boat was floating gently downstream","The boat was drifting in circles"], a:1, ex:"A leaf on a waterfall is thrown violently up and down with no control — showing how the sea tossed the boat."},
{q:"How many survivors did Grace and her father rescue?", opts:["Two","Three","Four","Six"], a:2, ex:"They 'dragged four half-drowned survivors aboard'."},
{q:"What does the word 'swamped' mean in the fifth paragraph?", opts:["Filled with water","Turned around","Stuck on the rocks","Blown off course"], a:0, ex:"A boat that is swamped is flooded or overwhelmed with water — it nearly sank twice."},
{q:"How did Grace feel about becoming famous?", opts:["Delighted and proud","She did not understand or want the fuss","Angry with her father","Eager for more attention"], a:1, ex:"She became famous 'quite against her wishes' and 'never understood the fuss'."},
{q:"Which word best describes Grace's character?", opts:["Boastful","Selfish","Brave and modest","Fearful"], a:2, ex:"She risks her life to save strangers (brave) yet sees it as ordinary duty, not heroism (modest)."},
{q:"What does the final sentence tell us about how Grace saw her actions?", opts:["As a chance to become famous","As simply her duty as a keeper's daughter","As something she regretted","As the bravest thing anyone had done"], a:1, ex:"To Grace it 'was not heroism' but 'simply what the daughter of a lighthouse keeper was for'."}
]);

/* ---------------- PAPER 8 ---------------- */
ENG_PASSAGES.push({title:"How Volcanoes Work", body:`
<p>Beneath the solid ground on which we walk lies a world of astonishing heat. Only a few dozen miles down, the temperature is high enough to melt rock into a thick, glowing liquid called magma. Most of the time this molten rock stays trapped far below the surface. Occasionally, however, it finds a way out — and when it does, the result is a volcano.</p>
<p>The Earth's outer shell is not a single unbroken layer. Instead it is cracked into enormous pieces, rather like the cracked shell of a boiled egg, and these pieces — called tectonic plates — drift very slowly across the molten rock beneath. Most volcanoes form at the edges of these plates. Where two plates pull apart, or where one is forced down beneath another, magma can rise through the gaps and cracks towards the surface.</p>
<p>As magma rises, gases trapped inside it begin to expand, exactly as the bubbles in a fizzy drink expand when you unscrew the cap. If the magma is thin and runny, these gases escape gently, and the volcano oozes slow rivers of lava that people can sometimes outwalk. But if the magma is thick and sticky, the gases become trapped until the pressure is enormous — and then the volcano erupts with terrifying violence, hurling ash, rock and gas miles into the sky.</p>
<p>Volcanoes have long been feared, and with good reason: a single large eruption can bury entire cities, as happened to the Roman town of Pompeii in AD 79. Yet volcanoes also give as much as they take. The ash they scatter breaks down over centuries into some of the richest farming soil on Earth, which is why people continue to live and grow crops in their shadow. Volcanic rock is used for building; volcanic heat is tapped to make electricity; and it was volcanoes, erupting over billions of years, that helped create the very atmosphere we breathe.</p>
<p>Today, scientists called volcanologists keep constant watch over the world's most dangerous volcanoes, measuring tiny earthquakes, swelling ground and escaping gases for the warning signs of an eruption. They cannot yet stop a volcano — no one can — but by predicting when one may erupt, they can give people the most precious gift of all: enough time to escape.</p>`});
ENG_PAPERS.push([
{q:"What is magma?", opts:["A type of volcanic ash","Melted rock beneath the surface","A crack in the Earth's shell","A gas trapped in the ground"], a:1, ex:"Magma is 'a thick, glowing liquid' — rock melted by the great heat below the surface."},
{q:"The Earth's outer shell is compared to what everyday object?", opts:["A fizzy drink","The cracked shell of a boiled egg","A river","A loaf of bread"], a:1, ex:"It is 'cracked into enormous pieces, rather like the cracked shell of a boiled egg'."},
{q:"What are the huge cracked pieces of the Earth's shell called?", opts:["Volcanoes","Magma chambers","Tectonic plates","Lava flows"], a:2, ex:"'These pieces [are] called tectonic plates.'"},
{q:"Where do most volcanoes form?", opts:["In the middle of tectonic plates","At the edges of tectonic plates","Only under the sea","At the North and South Poles"], a:1, ex:"'Most volcanoes form at the edges of these plates.'"},
{q:"Why does the writer compare the gases in magma to a fizzy drink?", opts:["Both are good to drink","Both are cold","The trapped gases expand and bubble just like a fizzy drink when opened","Both are brightly coloured"], a:2, ex:"Gases in rising magma expand 'exactly as the bubbles in a fizzy drink expand when you unscrew the cap'."},
{q:"What kind of magma produces the most violent eruptions?", opts:["Thin and runny magma","Thick and sticky magma","Cold magma","Magma with no gas in it"], a:1, ex:"Thick, sticky magma traps the gases until the pressure is enormous, causing a violent eruption."},
{q:"What happened to Pompeii in AD 79?", opts:["It was flooded by lava rivers","It was buried by a large eruption","It was rebuilt on volcanic soil","It was saved by volcanologists"], a:1, ex:"'A single large eruption can bury entire cities, as happened to the Roman town of Pompeii in AD 79.'"},
{q:"Why do people continue to live near volcanoes?", opts:["The volcanoes protect them from enemies","Volcanic ash creates very rich farming soil","It is against the law to move away","Volcanoes never erupt twice"], a:1, ex:"The ash breaks down into 'some of the richest farming soil on Earth', so people farm in the volcano's shadow."},
{q:"According to the passage, which of these is NOT given as a benefit of volcanoes?", opts:["Rich soil for farming","Rock for building","Heat for making electricity","A safe place to shelter from storms"], a:3, ex:"The passage lists soil, building rock, electricity and even the atmosphere — but never shelter from storms."},
{q:"What is a volcanologist?", opts:["A person who causes eruptions","A scientist who studies and watches volcanoes","A type of volcanic rock","A machine that measures earthquakes"], a:1, ex:"'Scientists called volcanologists keep constant watch over the world's most dangerous volcanoes.'"},
{q:"What 'most precious gift' can volcanologists give people?", opts:["The power to stop eruptions","Enough warning time to escape","Free electricity","Richer farmland"], a:1, ex:"By predicting eruptions they give people 'enough time to escape' — they cannot stop a volcano."},
{q:"What is the main purpose of this passage?", opts:["To persuade people to move away from volcanoes","To tell an exciting story about Pompeii","To explain how volcanoes form and why they matter","To describe the life of a volcanologist"], a:2, ex:"It is an informative text explaining what causes volcanoes and their effects, both harmful and helpful."}
]);

/* ---------------- PAPER 9 ---------------- */
ENG_PASSAGES.push({title:"The Boy Who Drew Machines", body:`
<p>In the small town of Vinci, in the hills of Italy, there once lived a boy who could not stop asking questions. Why did birds not fall from the sky? How did water know to flow downhill? What lay behind the blue curtain of the horizon? His name was Leonardo, and while the other children played, he filled sheet after sheet with drawings of everything he saw: swirling water, the veins of a leaf, the muscles of a horse's leg.</p>
<p>Leonardo's notebooks were unlike anyone else's. He wrote from right to left, in mirror writing that could only be read by holding the page up to a looking-glass — perhaps to keep his ideas secret, perhaps simply because he was left-handed and it came more easily. Between the lines of writing crawled the strangest inventions: a machine with beating wings that a man might strap to his back and fly; a horseless cart that moved by itself; a diving suit for walking on the seabed; even a device very like the helicopter, three hundred years before anyone built an engine that could lift one.</p>
<p>Most of these machines were never made. The materials of Leonardo's time were too heavy, and the power to drive them did not yet exist. His flying machine would never have left the ground. Yet this hardly seems to matter. What Leonardo truly possessed was not the ability to build, but the ability to imagine — to look at a bird and see, hidden inside it, the secret of flight; to look at the world as it was and picture the world as it might one day become.</p>
<p>He was, of course, also one of the greatest painters who ever lived. But it would be a mistake to think of Leonardo as a painter who happened to like machines, or an inventor who happened to paint. To him there was no difference. Studying how light fell on a curved surface made him a better engineer; understanding how muscles moved made him a better artist. The world, to Leonardo, was a single glorious puzzle, and every subject was simply another window onto the same great mystery.</p>
<p>Five hundred years later, we still open his notebooks and marvel. Not because he gave us working machines — he did not — but because he reminds us of something easy to forget: that curiosity, followed far enough, is a kind of genius all its own.</p>`});
ENG_PAPERS.push([
{q:"Where did Leonardo grow up?", opts:["In the city of Rome","In the town of Vinci, in Italy","On a farm in France","By the seaside"], a:1, ex:"'In the small town of Vinci, in the hills of Italy, there once lived a boy…'"},
{q:"What did Leonardo do while the other children played?", opts:["He slept","He filled sheets with drawings of everything he saw","He built real flying machines","He read library books"], a:1, ex:"'While the other children played, he filled sheet after sheet with drawings.'"},
{q:"What was unusual about the way Leonardo wrote?", opts:["He wrote in code numbers","He wrote from right to left in mirror writing","He never wrote anything down","He wrote only in Latin"], a:1, ex:"'He wrote from right to left, in mirror writing that could only be read by holding the page up to a looking-glass.'"},
{q:"The passage suggests two possible reasons for his mirror writing. Which pair is correct?", opts:["To save ink, or to write faster","To keep ideas secret, or because he was left-handed","To copy his teacher, or to confuse thieves","Because he was tired, or because he was bored"], a:1, ex:"'Perhaps to keep his ideas secret, perhaps simply because he was left-handed.'"},
{q:"Which of these inventions is described in his notebooks?", opts:["A telephone","A diving suit for walking on the seabed","A steam train","A printing press"], a:1, ex:"Among his inventions was 'a diving suit for walking on the seabed'."},
{q:"Why were most of Leonardo's machines never built?", opts:["He lost the drawings","The materials were too heavy and there was no power to drive them","He was forbidden by law","He preferred painting"], a:1, ex:"'The materials of Leonardo's time were too heavy, and the power to drive them did not yet exist.'"},
{q:"According to the writer, what did Leonardo 'truly possess'?", opts:["Great wealth","The ability to imagine","A powerful engine","A large workshop"], a:1, ex:"'What Leonardo truly possessed was not the ability to build, but the ability to imagine.'"},
{q:"What does the writer mean by saying 'to look at a bird and see, hidden inside it, the secret of flight'?", opts:["Leonardo dissected birds for food","Leonardo could study nature to understand how things worked","Leonardo kept birds as pets","Leonardo could actually fly"], a:1, ex:"It means he looked at nature and worked out the principles behind it — here, how flight works."},
{q:"Why is it 'a mistake to think of Leonardo as a painter who happened to like machines'?", opts:["He never really painted","To him, art and science were not separate things","He disliked painting","He only cared about machines"], a:1, ex:"'To him there was no difference' — his art and his science fed each other as one pursuit."},
{q:"How did studying muscles help Leonardo, according to the passage?", opts:["It made him a better cook","It made him a better artist","It made him a better writer","It made him famous"], a:1, ex:"'Understanding how muscles moved made him a better artist.'"},
{q:"What does the writer say is the real reason we still marvel at his notebooks?", opts:["Because his machines all work","Because they remind us curiosity is a kind of genius","Because they are worth a lot of money","Because they are written in code"], a:1, ex:"We marvel because they remind us 'that curiosity, followed far enough, is a kind of genius all its own'."},
{q:"The phrase 'a single glorious puzzle' describes how Leonardo saw…", opts:["his paintings","the whole world","his notebooks","the town of Vinci"], a:1, ex:"'The world, to Leonardo, was a single glorious puzzle' — every subject a window onto the same mystery."}
]);

/* ---------------- PAPER 10 ---------------- */
ENG_PASSAGES.push({title:"The Last Train Home", body:`
<p>Priya knew she had cut it fine. The clock above the station entrance read 11:52, and the last train left at 11:55. She flew down the steps two at a time, her bag thumping against her hip, and burst onto the platform just as the guard raised his whistle to his lips.</p>
<p>"Wait!" she gasped. "Please!"</p>
<p>The guard, a round man with kind eyes and an enormous moustache, paused, looked at her, and lowered the whistle. "In you get, then. Quick about it." Priya tumbled through the nearest door, and with a hiss and a lurch the train began to move.</p>
<p>The carriage was almost empty. An elderly woman dozed in one corner beneath a tartan blanket; a young man in paint-spattered overalls stared out of the window; and near the middle sat a small girl of perhaps seven, entirely alone, clutching a battered cardboard suitcase and swinging her feet, which did not quite reach the floor. It was the girl who caught Priya's attention, because she was crying — not loudly, but in the silent, hopeless way of someone who has been crying for a long time and no longer expects anyone to notice.</p>
<p>Priya hesitated. It was late; she was tired; it was, strictly speaking, none of her business. Then she thought of how she would feel, seven years old and alone on a night train, and she crossed the carriage and sat down opposite the child.</p>
<p>"That's a very fine suitcase," she said. "Where are you off to?"</p>
<p>The girl looked up, startled, and wiped her nose on her sleeve. "Grandma's," she whispered. "But I got on the wrong train, and now I don't know where I am, and the man said this train doesn't stop at Grandma's station." A fresh tear rolled down her cheek.</p>
<p>Priya's heart turned over. But she smiled, and kept her voice light and certain, the way her own mother used to. "Well, then," she said, "it's lucky you met me, because I happen to be extremely good at finding grandmas. The very first thing we'll do, when we reach the next station, is telephone yours. Now — does she keep a cat, this grandma of yours? Because grandmas with cats are always the easiest to find."</p>
<p>The girl gave a small, wet laugh. And though the night outside was black and the train rushed on into the dark, the distance to Grandma's house suddenly seemed a great deal shorter than it had a moment before.</p>`});
ENG_PAPERS.push([
{q:"What time did the last train leave?", opts:["11:52","11:53","11:55","12:00"], a:2, ex:"'The last train left at 11:55', and the clock read 11:52 as Priya arrived."},
{q:"How is the guard described?", opts:["Tall and stern","Round, with kind eyes and an enormous moustache","Thin and impatient","Young and cheerful"], a:1, ex:"He is 'a round man with kind eyes and an enormous moustache'."},
{q:"Why did the guard let Priya on the train?", opts:["She showed him a ticket","He took pity on her and lowered his whistle","She was a regular passenger","The train was delayed"], a:1, ex:"He 'paused, looked at her, and lowered the whistle', telling her to get in quickly."},
{q:"How was the little girl crying?", opts:["Loudly and angrily","Silently and hopelessly, as if long used to it","With great dramatic sobs","Only pretending to cry"], a:1, ex:"She cried 'in the silent, hopeless way of someone who has been crying for a long time'."},
{q:"What detail shows how young and small the girl is?", opts:["She wore paint-spattered overalls","Her feet did not quite reach the floor","She slept under a tartan blanket","She carried a whistle"], a:1, ex:"She sat 'swinging her feet, which did not quite reach the floor' — a small child on an adult seat."},
{q:"What reasons does Priya give herself for NOT getting involved?", opts:["She was hungry and cross","It was late, she was tired, and it was none of her business","She did not like children","She was afraid of the guard"], a:1, ex:"'It was late; she was tired; it was, strictly speaking, none of her business.'"},
{q:"What finally makes Priya cross the carriage to help?", opts:["The guard tells her to","She imagines being seven and alone on a night train herself","The girl calls out to her","The elderly woman asks her to"], a:1, ex:"'She thought of how she would feel, seven years old and alone on a night train.'"},
{q:"What has gone wrong for the little girl?", opts:["She has lost her suitcase","She got on the wrong train and it won't stop at her grandma's station","She has missed her grandma's birthday","She has forgotten her ticket"], a:1, ex:"'I got on the wrong train… the man said this train doesn't stop at Grandma's station.'"},
{q:"Why does Priya ask whether the grandma keeps a cat?", opts:["She is afraid of cats","To gently distract and reassure the girl with a light, playful question","She wants to visit the cat","She is checking the girl is telling the truth"], a:1, ex:"She keeps her voice 'light and certain' and turns it into a game, to comfort the frightened child."},
{q:"'Priya's heart turned over.' What does this expression tell us?", opts:["Priya felt suddenly unwell","Priya was moved with pity for the girl","Priya changed her mind about helping","Priya was frightened of the girl"], a:1, ex:"It means she was struck by a strong feeling — here, deep sympathy for the child."},
{q:"How does the girl react to Priya's words about grandmas and cats?", opts:["She cries harder","She gives a small, wet laugh","She runs away","She falls asleep"], a:1, ex:"'The girl gave a small, wet laugh' — a laugh through her tears."},
{q:"What does the last sentence suggest has changed?", opts:["The train has arrived at Grandma's","The girl no longer feels so alone and afraid","Priya has decided to leave the train","The night has become bright"], a:1, ex:"The distance 'seemed a great deal shorter than it had a moment before' — kindness has made the girl's problem feel smaller."}
]);

/* ---------------- PAPER 11 ---------------- */
ENG_PASSAGES.push({title:"The Great Migration", body:`
<p>Every year, across the plains of East Africa, one of the most extraordinary events in the natural world unfolds. More than a million wildebeest, together with hundreds of thousands of zebra and gazelle, gather into a single vast herd and begin an enormous journey in search of fresh grass and water. This is the Great Migration, and it never truly ends: the animals travel in a great circle, roughly a thousand miles around, following the rains from one grazing ground to the next, year after year, for as long as anyone can remember.</p>
<p>The journey is far from easy. The herds must cross wide rivers where crocodiles, some of them older than the oldest person in a nearby village, lie waiting beneath the muddy water. They must run the gauntlet of lions, cheetahs and hyenas, who follow the migration as a travelling market follows a crowd. Tens of thousands of animals die each year — the old, the sick, the very young and the merely unlucky. Yet still the herd moves on, because to stop is to starve.</p>
<p>Why do they do it? The answer lies in the rain. East Africa has two rainy seasons and two dry ones, and grass grows only where the rain has recently fallen. No single patch of land can feed a million wildebeest for long. By keeping constantly on the move, the herd is always arriving at fresh pasture just as the grass there is at its greenest, and leaving just as it runs out. The migration, in other words, is not a journey with a destination. It is the destination — an endless loop, tuned over countless generations to the rhythm of the rains.</p>
<p>The wildebeest themselves seem unremarkable animals: ungainly, awkward-looking creatures that early European visitors unkindly described as if assembled from the spare parts of nobler beasts. But there is a deep intelligence in the herd as a whole. No leader gives the order to move; instead, the decision seems to ripple through the entire group at once, as though a million animals shared a single mind. Scientists call this 'swarm intelligence', and they still do not fully understand it.</p>
<p>Watching the migration, it is impossible not to feel that one is witnessing something very ancient — a pattern of movement older than farming, older than cities, older than history itself. The wildebeest have been walking this circle since long before there were people to watch them. Long after us, in all likelihood, they will be walking it still.</p>`});
ENG_PAPERS.push([
{q:"Roughly how many wildebeest take part in the Great Migration?", opts:["A few thousand","More than a million","Exactly one hundred thousand","Ten million"], a:1, ex:"'More than a million wildebeest… gather into a single vast herd.'"},
{q:"What is the shape of the route the animals follow?", opts:["A straight line north","A great circle of roughly a thousand miles","A zigzag across the desert","A short there-and-back trip"], a:1, ex:"'The animals travel in a great circle, roughly a thousand miles around.'"},
{q:"What are the animals searching for as they travel?", opts:["A safe place to sleep","Fresh grass and water","Other herds to join","Shelter from the sun"], a:1, ex:"They journey 'in search of fresh grass and water'."},
{q:"The writer compares the predators following the herd to…", opts:["a travelling market following a crowd","a river following its banks","soldiers following orders","children following a teacher"], a:0, ex:"The lions, cheetahs and hyenas 'follow the migration as a travelling market follows a crowd'."},
{q:"According to the passage, why does the herd keep moving despite the dangers?", opts:["Because a leader forces them to","Because to stop is to starve","Because they enjoy travelling","Because people drive them on"], a:1, ex:"'Still the herd moves on, because to stop is to starve.'"},
{q:"Why can no single patch of land feed the herd for long?", opts:["The animals are too fussy","Grass grows only where rain has recently fallen, and a million animals soon eat it all","The soil is poisonous","Farmers own all the land"], a:1, ex:"Grass grows only where rain has recently fallen, and 'no single patch of land can feed a million wildebeest for long'."},
{q:"What does the writer mean by 'The migration… is not a journey with a destination. It is the destination'?", opts:["The animals never actually move","The endless circular journey is the whole point, not a route to somewhere else","The animals are lost","They are trying to reach a particular city"], a:1, ex:"There is no end point; the never-ending loop, tuned to the rains, is itself the way the animals survive."},
{q:"How did early European visitors unkindly describe the wildebeest?", opts:["As the most beautiful animals in Africa","As if assembled from the spare parts of nobler beasts","As too dangerous to approach","As impossible to count"], a:1, ex:"They described them 'as if assembled from the spare parts of nobler beasts' — an insulting comparison."},
{q:"How does the herd seem to decide when to move?", opts:["The oldest wildebeest gives a signal","A decision seems to ripple through the whole group at once","The lions chase them into moving","They wait for a human guide"], a:1, ex:"'No leader gives the order… the decision seems to ripple through the entire group at once.'"},
{q:"What do scientists call the herd's way of acting as one?", opts:["Herd instinct","Swarm intelligence","Group panic","Animal magic"], a:1, ex:"'Scientists call this \"swarm intelligence\", and they still do not fully understand it.'"},
{q:"What feeling does the writer say it is impossible to avoid when watching the migration?", opts:["Boredom","That one is witnessing something very ancient","Fear of the crocodiles","Pity for the lions"], a:1, ex:"'It is impossible not to feel that one is witnessing something very ancient.'"},
{q:"What does the final sentence suggest about the future of the migration?", opts:["It will soon come to an end","It will probably continue long after humans are gone","It depends on human protection","It changes its route every year"], a:1, ex:"'Long after us, in all likelihood, they will be walking it still.'"}
]);

/* ---------------- PAPER 12 ---------------- */
ENG_PASSAGES.push({title:"The Inheritance", body:`
<p>When old Mr Abernathy died, he left his entire fortune — and it was a considerable one — to be divided between his two nephews. But the will contained a peculiar condition. The money would go, it said, to whichever of the two young men could fill a large empty barn 'most completely, at the least expense', using whatever he chose. They would have one day each, and the lawyer would judge.</p>
<p>The elder nephew, Marcus, was a practical sort, and he set about the task with energy. He hired three carts and spent the whole day hauling load after load of straw from a neighbouring farm, until the barn was stacked to shoulder height and the air was thick with golden dust. It had cost him a good deal of money, and by evening he was exhausted, but he surveyed his work with satisfaction. Surely, he thought, no one could fill the barn more fully than that.</p>
<p>The younger nephew, Jonah, arrived the next morning empty-handed, and the lawyer raised an eyebrow. Jonah asked only that the great barn doors be shut, and that every crack and window be covered until the building was as dark as midnight. Then, from his pocket, he produced a single small candle and a box of matches. He struck a match, lit the candle, and held it up. At once, warm light welled into every corner of the barn, filling the whole vast space from floor to rafters, leaving not one shadow untouched.</p>
<p>"You asked me to fill the barn most completely and at the least expense," said Jonah quietly. "Straw fills only the space it takes up. But light fills everything, and touches every corner at once — and it has cost me a single candle."</p>
<p>The lawyer looked from the towering, costly heap of straw to the small, steady flame that had somehow filled the entire barn, and he closed his book. The fortune, he declared, belonged to Jonah — not because he had been the more hardworking, for plainly he had not, but because he had understood something his brother had missed: that the cleverest answer to a problem is rarely the most obvious one, and almost never the most expensive.</p>
<p>Marcus, to his credit, laughed aloud when he understood, and shook his brother warmly by the hand. "I filled the barn with my back," he admitted. "You filled it with your head. I can hardly complain that the better man won."</p>`});
ENG_PAPERS.push([
{q:"What strange condition did Mr Abernathy's will contain?", opts:["The nephews had to build a new barn","The fortune went to whoever could fill the barn most completely at the least expense","The nephews had to sell the barn","The money went to the elder nephew only"], a:1, ex:"The money would go to whoever could fill the barn 'most completely, at the least expense'."},
{q:"How long did each nephew have for the task?", opts:["One hour","One day each","One week","As long as they liked"], a:1, ex:"'They would have one day each, and the lawyer would judge.'"},
{q:"How did Marcus try to fill the barn?", opts:["With water","With hundreds of candles","With load after load of straw","With sand"], a:2, ex:"He 'spent the whole day hauling load after load of straw', stacking it shoulder-high."},
{q:"What does the phrase 'a practical sort' tell us about Marcus?", opts:["He was lazy","He was down-to-earth and hard-working","He was dishonest","He was very rich already"], a:1, ex:"'Practical' here means sensible and hands-on; he tackled the job with energy and hard graft."},
{q:"Why did the lawyer raise an eyebrow when Jonah arrived?", opts:["Jonah was late","Jonah arrived empty-handed","Jonah brought three carts","Jonah refused to take part"], a:1, ex:"'The younger nephew, Jonah, arrived the next morning empty-handed, and the lawyer raised an eyebrow' — surprised he had brought nothing."},
{q:"What did Jonah ask to be done to the barn first?", opts:["To fill it with straw","To make it as dark as midnight by covering every crack and window","To knock down one wall","To fill it with water"], a:1, ex:"He asked that the doors be shut and 'every crack and window be covered until the building was as dark as midnight'."},
{q:"How did Jonah fill the barn?", opts:["With golden dust","With the light of a single candle","With his three carts","With warm air"], a:1, ex:"He lit a single candle, and 'warm light welled into every corner of the barn… from floor to rafters'."},
{q:"What is Jonah's key point about the difference between straw and light?", opts:["Straw is cheaper than light","Light fills every corner at once, while straw fills only the space it occupies","Straw is heavier than light","Light is more colourful than straw"], a:1, ex:"'Straw fills only the space it takes up. But light fills everything, and touches every corner at once.'"},
{q:"Why did the lawyer award the fortune to Jonah?", opts:["Because Jonah worked hardest","Because Jonah was the elder brother","Because Jonah understood that the cleverest answer is rarely the most obvious or expensive","Because Marcus broke the rules"], a:2, ex:"He won 'not because he had been the more hardworking' but because he grasped that clever solutions are rarely the obvious, expensive ones."},
{q:"What is the meaning of Marcus's remark, 'I filled the barn with my back… You filled it with your head'?", opts:["Marcus used strength while Jonah used cleverness","Marcus hurt his back lifting straw","Jonah was taller than Marcus","Both brothers cheated"], a:0, ex:"'With my back' means by physical labour; 'with your head' means by thinking cleverly — Marcus admits Jonah's brains beat his brawn."},
{q:"What does Marcus's reaction at the end tell us about his character?", opts:["He was a bitter and jealous man","He was a good sport who could admit he had been outwitted","He refused to accept the decision","He never understood what had happened"], a:1, ex:"He 'laughed aloud' and shook Jonah's hand, saying he could 'hardly complain that the better man won' — generous in defeat."},
{q:"Which saying best sums up the message of this story?", opts:["Many hands make light work","Hard work always wins in the end","Brains are better than brute force","Money cannot buy happiness"], a:2, ex:"The tale shows cleverness (Jonah's candle) beating sheer effort and expense (Marcus's straw) — brains over brute force."}
]);
